<a href="https://colab.research.google.com/github/piyush-raj04/Python/blob/main/Pandas_working_withhtml.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Pandas working with HTML

In [21]:
import pandas as pd

In [23]:
import requests

url = "https://en.wikipedia.org/wiki/Mobile_country_code"
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'}

response = requests.get(url, headers=headers)
html=pd.read_html(response.text)

/tmp/ipykernel_753/3288757203.py:7: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  html=pd.read_html(response.text)

In [24]:
type(html)

list

In [27]:
html[1]

,Mobile country code,Country,ISO 3166,Mobile network codes,National MNC authority,Remarks
0,289,A Abkhazia,GE-AB,List of mobile network codes in Abkhazia,NaN,MCC is not listed by ITU
1,412,Afghanistan,AF,List of mobile network codes in Afghanistan,NaN,NaN
2,276,Albania,AL,List of mobile network codes in Albania,NaN,NaN
3,603,Algeria,DZ,List of mobile network codes in Algeria,NaN,NaN
4,544,American Samoa (United States of America),AS,List of mobile network codes in American Samoa,NaN,NaN
...,...,...,...,...,...,...
247,452,Vietnam,VN,List of mobile network codes in the Vietnam,NaN,NaN
248,543,W Wallis and Futuna,WF,List of mobile network codes in Wallis and Futuna,NaN,NaN
249,421,Y Yemen,YE,List of mobile network codes in the Yemen,NaN,NaN
250,645,Z Zambia,ZM,List of mobile network codes in Zambia,NaN,NaN
251,648,Zimbabwe,ZW,List of mobile network codes in Zimbabwe,NaN,NaN

In [11]:
import requests

url = "https://en.wikipedia.org/wiki/Economy_of_the_United_States"
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'}

response = requests.get(url, headers=headers)
html = pd.read_html(response.text, match="Government debt")

/tmp/ipykernel_753/631750130.py:7: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  html = pd.read_html(response.text, match="Government debt")

In [12]:
type(html)

list

In [13]:
html[0]

,0,1
0,"The nation's largest city, New York City, is c...","The nation's largest city, New York City, is c..."
1,Currency,"United States dollar (USD, $)"
2,Fiscal year,October 1 – September 30
3,Trade organizations,"WTO, G20, G7, OECD, USMCA, APEC and others"
4,Country group,Advanced economy[3] High-income economy[4]
5,Statistics,Statistics
6,Population,"342,818,500 (2026)[5]"
7,GDP,$32.38 trillion (nominal; 2026)[6] $32.38 tri...
8,GDP rank,1st (nominal; 2026) 2nd (PPP; 2026)
9,GDP growth,2.1% (2025)[6] 2.3% (2026f)[6] 2.1% (2027f)[6]
10,GDP per capita,"$94,430 (nominal; 2026)[6] $94,430 (PPP; 2026..."
11,GDP per capita rank,8th (nominal; 2026) 10th (PPP; 2026)
12,GDP per capita growth,1.6% (2025)[7]
13,GDP by sector,Services: 76.4% Industry: 17.6% Agriculture: 5...
14,GDP by component,Household consumption: 67.9% Government consum...
15,Inflation (CPI),3.4% (July 2026)[10]
16,Population below national poverty line,10.6% (2024)[11] 35.9 million (2024)[11]
17,Gini coefficient,"46.5 (2023, USCB)[12] 41.8 (2023, World Bank)..."
18,Human Development Index,0.938 (2023)[15] (17th) 0.832 IHDI (29th) (20...
19,Corruption Perceptions Index,65 out of 100 points (2024)[16] (rank 28th)
20,Labor force,"168,110,083 (2024)[17] 62.6% employment rate (..."
21,Labor force by occupation,Agriculture: 1.0% Industry: 19% Services: 80% ...
22,Unemployment,4.1% (August 2026)[17] 7.0 million unemployed...
23,Youth unemployment,9.1% (August 2026; 16 to 24 year-olds)[19]
24,Average gross salary,"$6,126, monthly[20] (2025)"
25,Average net salary,"$4,637, monthly[20] (2025)"
26,Median income,"$1,251 weekly[21] (full-time, 2026)"
27,Wage growth,"0.8% (hourly, 2025)[22]"
28,Final consumption expenditure,85.2% of GDP (2023)[9]
29,Gross capital formation,17.7% of GDP (2023)[9]
30,Yield curve,10-year bond 4.28% (April 2025)[23]
31,Purchasing Managers' Index,52.0 Manufacturing (May 2025)[24] 53.7 Servic...
32,Main industries,NaN
33,Further information High-technologypetroleumst...,Further information High-technologypetroleumst...
34,Further information,Further information
35,NaN,NaN
36,High-technologypetroleumsteelmotor vehiclesaer...,High-technologypetroleumsteelmotor vehiclesaer...
37,External,External
38,Exports,$3.430 trillion (2025)[25][26]
39,Export goods,Agricultural products 10.7%Fuels and mining pr...
40,Main export partners,European Union 18.8% Mexico 15.3% Canada 15.3%...
41,Imports,$4.341 trillion (2025)[25][26]
42,Import goods,Agricultural products 10.5%Fuels and mining pr...
43,Main import partners,European Union 18.4% Mexico 15.5% Canada 11.1%...
44,FDI stock,Inward: $367 billion (2021)[30] Outward: $403...
45,Current account,−$911.60 billion (2025)[28] −2.93% of GDP (20...
46,Gross external debt,$27 trillion (2023)[31]
47,Public finance,Public finance
48,Government debt,$40 trillion 121% of GDP (2024)[32]
49,Foreign reserves,$250 billion (2024)[33]
50,Budget balance,−6.4% of GDP (2024)[34]
51,Revenue,$8.720 trillion[32] 29.9% of GDP (2024)
52,Spending,$10.945 trillion[32] 37.5% of GDP (2024) U.S. ...
53,Economic aid,"donor: ODA, $35.26 billion (2017)[35]"
54,Credit rating,Standard & Poor's:[36] AA+ (Domestic) AA+ (For...
55,"All values, unless otherwise stated, are in US...","All values, unless otherwise stated, are in US..."

In [15]:
import requests

url = "https://en.wikipedia.org/wiki/Minnesota"
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'}

response = requests.get(url, headers=headers)
html=pd.read_html(response.text,match="Average daily maximum and minimum temperatures for selected cities in Minnesota")

/tmp/ipykernel_753/3557347058.py:7: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  html=pd.read_html(response.text,match="Average daily maximum and minimum temperatures for selected cities in Minnesota")

In [16]:
html[0]

              Location July (°F) July (°C) January (°F) January (°C)
0          Minneapolis     83/64     28/18         23/7       −4/−13
1           Saint Paul     83/63     28/17         23/6       −5/−14
2            Rochester     82/63     28/17         23/3       −5/−16
3               Duluth     76/55     24/13         19/1       −7/−17
4            St. Cloud     81/58     27/14        18/−1       −7/−18
5              Mankato     86/62     30/16         23/3       −5/−16
6  International Falls     77/52     25/11        15/−6       −9/−21

In [18]:
type(html[0])

pandas.core.frame.DataFrame

In [19]:
html[0].to_html('demo.html')