<a href="https://colab.research.google.com/github/piyush-raj04/Python/blob/main/Pythoncsv.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Python Pandas

In [ ]:
from io import StringIo

In [7]:
import pandas as pd
df=pd.read_csv("mercedesbenz.csv")
df.head()

,ID,y,X0,X1,X2,X3,X4,X5,X6,X8,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,0,130.81,k,v,at,a,d,u,j,o,...,0,0,1,0,0,0,0,0,0,0
1,6,88.53,k,t,av,e,d,y,l,o,...,1,0,0,0,0,0,0,0,0,0
2,7,76.26,az,w,n,c,d,x,j,x,...,0,0,0,0,0,0,1,0,0,0
3,9,80.62,az,t,n,f,d,x,l,e,...,0,0,0,0,0,0,0,0,0,0
4,13,78.02,az,v,n,f,d,h,d,n,...,0,0,0,0,0,0,0,0,0,0

In [8]:
type(df)

pandas.core.frame.DataFrame

In [9]:
data=('col1,col2,col3\n'
     'x,y,1\n'
     'a,b,2\n'
     'c,d,3')

In [10]:
type(data)

str

In [15]:
from io import StringIO
StringIO(data)

In [16]:
pd.read_csv(StringIO(data))

  col1 col2  col3
0    x    y     1
1    a    b     2
2    c    d     3

In [17]:
pd.read_csv(StringIO(data),)

  col1 col2  col3
0    x    y     1
1    a    b     2
2    c    d     3

In [18]:
data=('a,b,c,d\n'
          '1,2,3,4\n'
          '5,6,7,8\n'
          '9,10,11')

In [21]:
df=pd.read_csv(StringIO(data),dtype='object')

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   a       3 non-null      object
 1   b       3 non-null      object
 2   c       3 non-null      object
 3   d       2 non-null      object
dtypes: object(4)
memory usage: 228.0+ bytes

In [23]:
df.isnull().sum()

a    0
b    0
c    0
d    1
dtype: int64

In [25]:
df['a'][0]

'1'

In [26]:
data=('a,b,c,d\n'
          '1,2,3,4\n'
          '5,6,7,8\n'
          '9,10,11')

In [27]:
df=pd.read_csv(StringIO(data),dtype={'a':int,'b':float,'c':int})

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   a       3 non-null      int64
 1   b       3 non-null      float64
 2   c       3 non-null      int64
 3   d       2 non-null      float64
dtypes: float64(2), int64(2)
memory usage: 228.0 bytes

In [30]:
df.dtypes

a      int64
b    float64
c      int64
d    float64
dtype: object

In [31]:
data=('index,a,b,c\n'
        '4,apple,bat,5.7\n'
           '8,orange,cow,10')

In [34]:
pd.read_csv(StringIO(data),index_col=0)

            a    b     c
index
4       apple  bat   5.7
8      orange  cow  10.0

In [40]:
##useindexcol and usecols
pd.read_csv(StringIO(data),usecols=['a','b','c'],index_col=0)

          b     c
a
apple   bat   5.7
orange  cow  10.0